import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
     className={`${geistSans.variable} ${geistMono.variable} antialiased`}

    >
          <main>
          {children}
          </main>
          <Toaster />
      </body>
   

    </html>
  );
}
